name: myworkflow

on: push

jobs:
  build:
     runs-on: ubuntu-latest

     steps:
      - uses: actions/checkout@v5.0.0

      - name: run a sample github actions
      - run: echo "This workflow run successfully for this particular actions"

  
